#!/usr/bin/env bash

# https://coderwall.com/p/fkfaqq/safer-bash-scripts-with-set-euxo-pipefail
set -euo pipefail

# inspired by
# https://github.com/kylealwyn/dotfiles
# https://github.com/berfarah/dotfiles

for f in ~/dotfiles/bootstrap_steps/*; do source $f; done

all_steps=(
  "xcode"
  "homebrew"
  "chrome_extensions"
  "bash"
  "vim"
  "git"
  "nvm"
  "sublime"
  "gem"
)

for step in ${@-"${all_steps[@]}"}; do
  printf "Setting up $step\n"
  $"bootstrap_$step"
done

printf 'Done! some notes:\n'
printf 'Need to manually install "package controll" package in sublime for sublime to auto-download packages\n'
printf 'manually install chrome extension: https://github.com/iamadamdev/bypass-paywalls-chrome\n'

