#!/usr/bin/env bash

# inspired by
# https://github.com/kylealwyn/dotfiles
# https://github.com/berfarah/dotfiles

for f in ~/dotfiles/bootstrap_steps/*; do source $f; done

all_steps=(
  "xcode"
  "homebrew"
  "chrome_extensions"
  "bash"
  "vim"
  "git"
  "nvm"
  "sublime"
)

for step in ${@-"${all_steps[@]}"}; do
  printf "Setting up $step\n"
  $"bootstrap_$step"
done

printf 'Done! some notes:\n'
printf 'Need to manually install "package controll" package in sublime for sublime to auto-download packages\n'

